name: fix_my_city_backend
dependencies:
  - python=3.9
  - pip=21.1
  - psycopg2=2.8
  - pip:
      - Django==3.2
      - djangorestframework==3.12
      - djangorestframework-simplejwt==4.7
      - pyjwt===2.1.0
      - drf-yasg==1.20
      - Pillow==8.2
      - gunicorn==20.1
      - flake8==3.9
      - django-cors-headers
